export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

export const CREATE_COMPANY_BEGIN = 'CREATE_COMPANY_BEGIN'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_ERROR = 'CREATE_COMPANY_ERROR'

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

export const GET_USERS_BEGIN = 'GET_USERS_BEGIN'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'

export const GET_COMPANIES_BEGIN = 'GET_COMPANIES_BEGIN'
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS'

export const GET_JOB_DETAIL_BEGIN = 'GET_JOB_DETAIL_BEGIN'
export const GET_JOB_DETAIL_SUCCESS = 'GET_JOB_DETAIL_SUCCESS'

export const GET_COMPANY_DETAIL_BEGIN = 'GET_COMPANY_DETAIL_BEGIN'
export const GET_COMPANY_DETAIL_SUCCESS = 'GET_COMPANY_DETAIL_SUCCESS'

export const GET_USER_DETAIL_BEGIN = 'GET_USER_DETAIL_BEGIN'
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS'

export const SET_EDIT_JOB = 'SET_EDIT_JOB'
export const SET_EDIT_COMPANY = 'SET_EDIT_COMPANY'
export const SET_EDIT_USER = 'SET_EDIT_USER'

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN'
export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN'

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'

export const EDIT_COMPANY_BEGIN = 'EDIT_COMPANY_BEGIN'
export const EDIT_COMPANY_SUCCESS = 'EDIT_COMPANY_SUCCESS'
export const EDIT_COMPANY_ERROR = 'EDIT_COMPANY_ERROR'

export const EDIT_USER_BEGIN = 'EDIT_USER_BEGIN'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const SHOW_DASHBOARD_STATS_BEGIN = 'SHOW_DASHBOARD_STATS_BEGIN'
export const SHOW_DASHBOARD_STATS_SUCCESS = 'SHOW_DASHBOARD_STATS_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const GET_APPLIED_JOBS_BEGIN = 'GET_APPLIED_JOBS_BEGIN'
export const GET_APPLIED_JOBS_SUCCESS = 'GET_APPLIED_JOBS_SUCCESS'

export const APPLY_JOB_BEGIN = 'APPLY_JOB_BEGIN'
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS'
export const APPLY_JOB_ERROR = 'APPLY_JOB_ERROR'
